### ISSUE TITLE
Clarify open source licenses

### ISSUE THREAD

**Issue by stain** [CBICA/CmdParser#1]
In the folder `thirdparty/yaml-cpp` you seem to include source code from https://github.com/jbeder/yaml-cpp but have not complied with its [MIT license](https://github.com/jbeder/yaml-cpp/blob/master/LICENSE) - in particular:

> The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

You will need to include the LICENSE file for yaml-cpp, I would suggest as `thirdparty/yaml-cpp/LICENSE` and refer to that file from your own `LICENSE` like:

> yaml-cpp is distributed under the MIT License. See thirdparty/yaml-cpp/LICENSE for details.

Crucially,  it is not clear what is the source code for your *own* code.

Your https://github.com/CBICA/CmdParser/blob/master/LICENSE says:

> Software from CBICA will use one of the following licenses:
> 
1. SBIA Software License (governs most of CBICA Software) - https://www.med.upenn.edu/sbia/software-agreement.html
2. SBIA Non-Commercial Software License (governs some of CBICA Software) - https://www.med.upenn.edu/sbia/software-agreement-non-commercial.html

But you have not specified which of these licenses you are using. [include/cbicaCmdParser.cpp](https://github.com/CBICA/CmdParser/blob/master/include/cbicaCmdParser.cpp) says:

> Copyright (c) 2018 University of Pennsylvania. All rights reserved. <br>
> See COPYING file or http://www.med.upenn.edu/sbia/software/license.html

But neither the file `COPYING` or the URL exist.

It is also considered best-practice to include the actual license text in LICENSE - as we see those URLs can stop working.

BTW, none of those SBIA licenses are listed as an [approved OSI license](https://opensource.org/licenses/alphabetical) and so this repository would for most people not classify as "open source" and be a hindrance from using your code.

**Comment by sarthakpati** [comment]
Thank you for mentioning these. I have updated to make these changes. We will be working with OSI to get the SBIA license included (though it is worth mentioning that it is very similar to the BSD-style license).
